version = 1

[[ analyzers ]]
  name = 'python'
  enabled = true

[[ analyzers ]]
  name = 'docker'
  enabled = true

  [analyzers.meta]
  dockerfile_paths = [
    'docker/Dockerfile',
    'docker/Dockerfile.windows',
  ]

